# Generated by Django 4.1.3 on 2022-12-02 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=20, unique=True)),
                ('cnr', models.CharField(max_length=30)),
                ('first_petitioner', models.CharField(max_length=50)),
                ('first_respondent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Advocates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petitioner_counsel', models.CharField(max_length=128, null=True)),
                ('respondent_counsel', models.CharField(max_length=128, null=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecourts_api.casedetails')),
            ],
        ),
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_petitioner', models.CharField(max_length=128, null=True)),
                ('additional_respondent', models.CharField(max_length=128, null=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecourts_api.casedetails')),
            ],
        ),
    ]
