# Generated by Django 4.1.3 on 2022-12-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecourts_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocates',
            old_name='petitioner_counsel',
            new_name='counsel_name',
        ),
        migrations.RemoveField(
            model_name='advocates',
            name='respondent_counsel',
        ),
        migrations.AddField(
            model_name='advocates',
            name='counsel_for',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
