# Generated by Django 4.1.3 on 2022-12-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecourts_api', '0006_causelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default=None, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecourts_api.casedetails')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecourts_api.documents')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default=None, max_length=30)),
                ('page_no', models.CharField(default=None, max_length=3)),
                ('bookmark_label', models.CharField(default=None, max_length=255, null=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecourts_api.casedetails')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecourts_api.documents')),
            ],
        ),
    ]
