# Generated by Django 4.1.3 on 2022-12-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecourts_api', '0007_notes_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='note',
        ),
    ]
