# Generated by Django 4.1.3 on 2022-12-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecourts_api', '0008_remove_bookmarks_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='document_id',
        ),
    ]
