# Generated by Django 4.1.3 on 2022-12-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecourts_api', '0009_remove_notes_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='first_petitioner',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='first_respondent',
            field=models.CharField(max_length=128),
        ),
    ]
