# Generated by Django 4.1.3 on 2022-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecourts_api', '0010_alter_casedetails_first_petitioner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(default=None, max_length=512)),
            ],
        ),
    ]
