# Generated by Django 4.1.3 on 2023-06-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecourts_api', '0011_documentmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIndexes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=256)),
                ('page', models.BigIntegerField(default=None)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecourts_api.documents')),
            ],
        ),
    ]
